rest_client:
    resource: "@RestClientBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
articles:
    type:     rest
    resource: AppBundle\Controller\ArticleController
